ARG os=8.7.20221112
FROM aursu/rpmbuild:${os}-build

USER root

COPY SOURCES ${BUILD_TOPDIR}/SOURCES
COPY SPECS ${BUILD_TOPDIR}/SPECS

RUN chown -R $BUILD_USER ${BUILD_TOPDIR}/{SOURCES,SPECS}

USER $BUILD_USER
ENTRYPOINT ["/usr/bin/rpmbuild", "GeoIP-GeoLite-data.spec"]
CMD ["-ba"]
